apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{service_mesh_member_roll_namespaces}}-wildcard-gateway
  namespace: {{service_mesh_member_roll_namespaces}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
    hosts:
    - "*.{{openshift_apps_domain}}"
